[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
# other options your default profile might have

[profile.zksync]
src = 'src'
libs = ['lib']
solc-version = "0.8.24"
fallback_oz = true
is_system = false
mode = "3"
